WORD_DICT = {
    "NOT_OPT": "not",
    "none": "",
    "sum": "sumary",
    "max": "maximum", 
    "min": "minimum",
    "count": "the number",
    "avg": "average",
    "between": "is between",
    "=": "equal to",
    ">=": "greater than or equal to",
    "<=": "less than or equal to",
    "!=": "not equal to",
    ">": "greater than",
    "<": "less than",
    "not": "not",
    "in": "in",
    "like": "like",
    "except": "except",
    "union": "or",
    "intersect": "and",
    "desc_limit_1": "maximum",
    "asc_limit_1": "minimum",
    "desc_limit_n": "top",
    "asc_limit_n": "lowest",
    "and": "and",
    "or": "or",
    "of": "of",
    "all": "",
    "where": "that",
    "the": "the",
    "comma": ",",
    "what": "what are",
    "from": "from",
    "having": "that",
    "groupby": "of different",
    "orderby": "ordered by",
    "orderby_limit": "that have",
    "-": "minus",
    "+": "plus",
    "*": "multiple",
    "/": "divided by",
    "?": "?"
}